nodeLinker: 'node-modules'
ignore-engines: true
# supportedArchitectures:
#   os:
#     - current
#     - darwin
#     - linux
#     - win32
#   cpu:
#     - current
#     - x64
#     - ia32
#     - arm64
