yarnPath: .yarn/releases/yarn-4.1.0.cjs
nodeLinker: 'node-modules'
# supportedArchitectures:
#   os:
#     - current
#     - darwin
#     - linux
#     - win32
#   cpu:
#     - current
#     - x64
#     - ia32
#     - arm64
