# Commented it out because `version` is obsolete
# version: "3.9"
services:
  younagi_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_DIR=workspace
        - USERNAME=dev
        - USER_UID=1001
        - USER_GID=1001
    environment:
      - COMPOSE_PROJECT_NAME=app
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      # - node-modules-data:/workspace/node_modules
    user: dev
# volumes:
#   node-modules-data:
