# Commented it out because `version` is obsolete
# version: "3.9"
services:
  younagi_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_DIR=workspace
        - USERNAME=dev
        - USER_UID=1001
        - USER_GID=1001
    environment:
      - COMPOSE_PROJECT_NAME=app
    working_dir: /workspace
    volumes:
      - project-data:/workspace:consistent
      # - .:/workspace:cached
    user: dev
  # db:
  #   container_name: younagi-db
  #   image: sqlite:latest
  #   volumes:
  #     - db-data:/var/lib/sqlite/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
volumes:
  project-data:
  # db-data:
