// Generated by Wrangler on Fri Aug 02 2024 06:25:18 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	UNSPLASH_API_ACCESS_KEY: string;
	TURNSTILE_SITE_KEY: string;
	PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	BREVO_API_KEY: string;
	MY_CUSTOM_EMAIL_ADDRESS: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	D1_DB_ID: string;
	D1_DB_API_TOKEN: string;
	LOCAL_DB_PATH: string;
	DB: D1Database;
}
