// Generated by Wrangler on Mon Aug 05 2024 03:58:54 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	MY_EMAIL_ADDRESS: string;
	MY_CUSTOM_EMAIL_ADDRESS: string;
	MAIL_OAUTH_CLIENT_ID: string;
	MAIL_OAUTH_CLIENT_SECRET: string;
	MAIL_OAUTH_REFRESH_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	D1_DB_ID: string;
	D1_DB_API_TOKEN: string;
	LOCAL_DB_PATH: string;
	DB: D1Database;
}
