name = "younagi-worker"
type = "javascript"
workers_dev = true

[build]
command = "pnpm run build:worker"

[[build.upload]]
format = "service-worker"
dir = "./dist"
main = "submitForm.js"

route = { pattern = "https://younagi.dev/api/submit-form", zone_name = "", script = "younagi-worker" }
