name = "younagi-worker"
workers_dev = true
# type = "javascript"

[build]
command = "pnpm run build:worker"

[[build.upload]]
dir = "./dist"
# format = "service-worker"
# main = "submitForm.js"

[[routes]]
pattern = "https://younagi.dev/api/submit-form"
zone_name = ""
script = "younagi-worker"
