name = "younagi-worker"
workers_dev = true
main = "./dist/api/submitForm.js"
# type = "javascript"

routes = [
  { pattern = "younagi.dev/*", zone_name = "younagi.dev", script = "younagi-worker" },
]

[build]
command = "pnpm run build:worker"

# dir = "./dist"
# format = "service-worker"
# main = "submitForm.js"
